name: 建構並推送 Docker 映像檔

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker_build:
    runs-on: ubuntu-latest

    steps:
      # 取得程式碼
      - name: 取得程式碼
        uses: actions/checkout@v5

      # 登入 GitHub Container Registry
      - name: 登入 GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 生成 Docker 標籤與標籤資訊
      - name: 生成 Docker 標籤與標籤資訊
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # 建構並推送 Docker 映像
      - name: 建構並推送 Docker 映像
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
